# Generated by Django 6.0.3 on 2026-06-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceo_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitylog',
            name='attempted_password',
        ),
    ]
