# Generated by Django 6.0.6 on 2026-06-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceo_portal', '0002_remove_securitylog_attempted_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('inquiries_count', models.IntegerField(default=0)),
                ('sourcing_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
