# Generated by Django 6.0.3 on 2026-05-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('category', models.CharField(choices=[('Cars', 'Cars'), ('Shoes', 'Shoes'), ('Fabrics', 'Fabrics'), ('Bags', 'Bags')], max_length=50)),
                ('image', models.ImageField(upload_to='products/')),
                ('description', models.TextField()),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items_requested', models.ManyToManyField(related_name='inquiries', to='ark_catalog.product')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
            },
        ),
    ]
