# Generated by Django 6.0.3 on 2026-05-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark_catalog', '0004_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourcingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('asset_class', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=100)),
                ('timeline', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Received', 'Request Received'), ('Researching', 'Market Researching'), ('Inspecting', 'Inspecting Assets'), ('Secured', 'Asset Secured'), ('Acquired', 'Acquired & Delivered'), ('Cancelled', 'Cancelled/Archived')], default='Received', max_length=20)),
                ('broker_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
