# Generated by Django 6.0.3 on 2026-06-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark_catalog', '0005_sourcingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='poster_image',
            field=models.ImageField(blank=True, help_text='Optional: Pin a custom poster image to this category card on the main portal page.', null=True, upload_to='categories/'),
        ),
    ]
