# Generated by Django 6.0.3 on 2026-06-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark_catalog', '0006_category_poster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in Nigerian Naira (₦). Leave blank to hide pricing.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_unit',
            field=models.CharField(blank=True, choices=[('per piece', 'Per Piece'), ('per yard', 'Per Yard'), ('per metre', 'Per Metre'), ('per kg', 'Per Kilogram'), ('per roll', 'Per Roll'), ('per set', 'Per Set'), ('per litre', 'Per Litre'), ('per pair', 'Per Pair'), ('per carton', 'Per Carton')], default='per piece', help_text='Unit of measurement for the quoted price.', max_length=20),
        ),
    ]
