# Generated by Django 6.0.6 on 2026-06-17 13:23

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ark_catalog', '0007_add_price_fields_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='full_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='lga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_unit',
            field=models.CharField(blank=True, choices=[('per piece', 'Per Piece'), ('per yard', 'Per Yard'), ('per set', 'Per Set'), ('per pair', 'Per Pair')], default='per piece', help_text='Unit of measurement for the quoted price.', max_length=20),
        ),
    ]
