"""
Django settings for global_ark project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Lightweight .env loader
env_path = BASE_DIR / '.env'
if env_path.exists():
    with open(env_path, 'r') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#'):
                key, val = line.split('=', 1)
                os.environ.setdefault(key.strip(), val.strip())

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', '(s^m362)rixn$a!@3nu_5^k$j^ehrt%=+u@m73fd4b(v3!6%@#')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,.herokuapp.com,.onrender.com,.arkglobalresources.com,.vercel.app').split(',')

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ark_catalog',
    'ceo_portal',
    'django_q',
    'cloudinary_storage',
    'cloudinary',
    'django.contrib.sitemaps',
    'whitenoise.runserver_nostatic', # Optional: for testing prod-like static locally
    'django_countries',
    'phonenumber_field',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Essential for hosting
    'ceo_portal.middleware.GatekeeperMiddleware',  # Custom Gatekeeper Middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'ceo_portal.middleware.AdminAutoLogoutMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'global_ark.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'ceo_portal.context_processors.security_context',
                'ark_catalog.context_processors.selection_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'global_ark.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Production Database Configuration
import dj_database_url
db_from_env = dj_database_url.config(conn_max_age=0)
DATABASES['default'].update(db_from_env)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Free Database Caching (Alternative to Redis)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'ark_cache_table',
    }
}

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Storage Configuration for Django 4.2+
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Prevent missing sourcemaps (e.g., chart.umd.js.map) from crashing collectstatic on Render
WHITENOISE_MANIFEST_STRICT = False

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
# Secure Executive Email Transmission enabled for ahmadmuftahu2005@gmail.com
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_TIMEOUT = 10  # Prevent Render workers from hanging indefinitely on slow SMTP connections
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# ARK Executive Configuration
ARK_EXECUTIVE_EMAIL = os.getenv('ARK_EXECUTIVE_EMAIL', EMAIL_HOST_USER)
WHATSAPP_NUMBER = os.getenv('WHATSAPP_NUMBER', '2348107707349')

# Mass Deployment Settings (Increased limits for bulk image uploads)
DATA_UPLOAD_MAX_NUMBER_FILES = 5000  # Allow up to 5000 files in one upload
DATA_UPLOAD_MAX_MEMORY_SIZE = 262144000  # Allow up to 250MB per request
FILE_UPLOAD_MAX_MEMORY_SIZE = 262144000

# Custom Security Door Configuration
SECRET_ADMIN_PATH = os.getenv('SECRET_ADMIN_PATH', 'vault-console')
SECRET_ADMIN_KEY = os.getenv('SECRET_ADMIN_KEY', 'ArkVanguard2026')

# Security Headers for Production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Cloudinary Media Storage Configuration (Always Active for Vercel)
STORAGES["default"]["BACKEND"] = "cloudinary_storage.storage.MediaCloudinaryStorage"

# django-cloudinary-storage strictly requires CLOUDINARY_STORAGE to be defined.
# We parse the CLOUDINARY_URL environment variable provided by Render or Vercel.
import urllib.parse
cloudinary_url = os.getenv('CLOUDINARY_URL', '')
if cloudinary_url:
    parsed_url = urllib.parse.urlparse(cloudinary_url)
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': parsed_url.hostname,
        'API_KEY': parsed_url.username,
        'API_SECRET': parsed_url.password,
    }
else:
    # Fallback if CLOUDINARY_URL is missing
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME', 'doezvrej5'),
        'API_KEY': os.getenv('CLOUDINARY_API_KEY', '929979217828284'),
        'API_SECRET': os.getenv('CLOUDINARY_API_SECRET', 'Zgd17qrkl9PtnD6415510651770'),
    }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Django-Q2 Configuration (Database Broker)
Q_CLUSTER = {
    'name': 'global_ark_cluster',
    'workers': 4,
    'recycle': 500,
    'timeout': 90,  # Ensure enough time for image processing
    'retry': 100,
    'compress': True,
    'save_limit': 250,
    'queue_limit': 500,
    'cpu_affinity': 1,
    'label': 'Django Q',
    'orm': 'default'  # Use Django's database as the broker
}

# Auth settings
LOGIN_URL = 'ceo_login'

# PhoneNumber default region
PHONENUMBER_DEFAULT_REGION = 'US'

import sys
if 'pytest' in sys.modules:
    DATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': ':memory:'}}
    SECURE_SSL_REDIRECT = False
    STORAGES = {'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'}, 'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'}}
